### ISSUE TITLE
Version conflict detected for Microsoft.CodeAnalysis.CSharp.Workspaces

### ISSUE THREAD

**Issue by knoxi** [egil/SourceFileFinder#2]
**Describe the bug or question**
We are using `Microsoft.CodeAnalysis` packages V3.7 and we have a nuget restore error because of a version conflict.

**Example:**
Add the latest `Microsoft.CodeAnalysis.CSharp.Features` package to the test project.

Results in this output:

Build Error:
```text
2>C:\Repos\Frontend\Tests\Frontend.BlazorControls.Tests.csproj : error NU1107: Version conflict detected for Microsoft.CodeAnalysis.CSharp.Workspaces. Install/reference Microsoft.CodeAnalysis.CSharp.Workspaces 3.7.0 directly to project Frontend.BlazorControls.Tests to resolve this issue. 
2>C:\Repos\Frontend\Tests\Frontend.BlazorControls.Tests.csproj : error NU1107:  Frontend.BlazorControls.Tests -> Microsoft.CodeAnalysis.CSharp.Features 3.7.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces (= 3.7.0) 
2>C:\Repos\Frontend\Tests\Frontend.BlazorControls.Tests.csproj : error NU1107:  Frontend.BlazorControls.Tests -> bunit.xunit 1.0.0-beta-9 -> SourceFileFinder 1.0.0-preview-1 -> Microsoft.CodeAnalysis 3.5.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces (= 3.5.0).

```

**Expected behavior:**
There should be no public dependencies for CodeAnalysis packages.

**Fix**:
Remove the public dependency of CodeAnalysis packages in SourceFileFinder

**Version info:**
 - Library version: 1.0.0-beta-9
 - .NET Core/Blazor version: 3.1

**Additional context:**
Update the package reference in the project file and set private assets to all.
````
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="3.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```

**Comment by egil** [comment]
Hey @knoxi 

Thanks for reporting this. The problem is actually in SourceFileFinder, a library I build to make it possible for Razor tests to be properly discovered by the xUnit test runner (https://github.com/egil/SourceFileFinder).

Since I am actually using Microsoft.CodeAnalysis in my code in that library, I cannot mark it as a private asset, as far as I know. But I might be able to make the version reference not be bound to a specific version, but to 3.x.

Any suggestions?

**Comment by egil** [comment]
Hi @knoxi 

I tried locally to reproduce, and it does indeed complain. The work-around is printed in the console when running `dotnet build`, which is to manually add a few extra references to force the version number to 3.7.0, e.g. this ,csproj compiles:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" Version="1.0.0-beta-9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="3.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="3.7.0" />    
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.7.0" />        
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

I am not sure why this is a problem though, since SourceFileFinder's dependency on `Microsoft.CodeAnalysis` is `>= 3.5.0`. Maybe @SimonCropp knows, he has lots more experience with NuGet than I.

Anyway, I am changing the package reference to this, which should also help:

```
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.*" />
```

**Comment by SimonCropp** [comment]
`<PackageReference Include="Microsoft.CodeAnalysis" Version="3.*" />` just to be clear, this will have the effect of "adding a dependency on the newest of v3 each time you deploy. it does not mean "my nuget is compat with all v3"
